### ISSUE TITLE
Rename starfeild-outpost-data to starfield-outpost-data

### ISSUE THREAD

**Issue by taosecurity** [Jaheay/starfeild-outpost-data#1]
Renaming 

starfeild-outpost-data 

to 

starfield-outpost-data

would help people find your code more easily?

Thank you.

**Comment by Jaheay** [comment]
Yeah, sadly I have already posted links to it in a number of places I can no longer modify - so, for now, I've moved it, and committed to this one a README.md directing to the new one. 

https://github.com/Jaheay/starfield-outpost-data

Also, I've read your blog for years, and you're the only person subscribed to my repo - haha, what a small world! Yourself and Dedoimedo are my must reads. Wonderful work there, it make my week to see an issue from you on my little project, on a throw away account, haha.
